#!/bin/sh

cd "$(dirname "$0")"

if ! command -v bindgen >/dev/null;  then
	echo "bindgen not found: you can install it by running: cargo install bindgen"
	exit 1
fi

bindgen ./NvFBC.h -o src/generated.rs
